print "Latexmkrc file for testing interaction between latex and biber\n",
      "on non-ASCII filenames.  John Collins 2024-09-26\n";

$aux_dir = $out2_dir = '';
$out_dir = 'résultats';
std_tex_cmds();

$pdf_mode = 1;

my $biber_bin = "../../bin/biber";
print "Using development version of biber, $biber_bin \n";
system $biber_bin, "--version";

$biber = "$biber_bin %O %S";


